# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 377aa9aa07d2bf7fa355101cbabc4e153c246555ea5efd701576a355d3db66cb3bcf8cd0b7a485dbc80821ce9c64557c7022cd5976ab0f96dba6d2c04819e50a

test:
  secret_key_base: e8e114911fc8bc1446517bfd389d3971bd72b7906528eaf424152c91eabeeeb8e4eba055fe5f62ea9bd04cc6a659419e6be702d5dd09d66d7ba8d13cfd8749e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
